### ISSUE TITLE
Few questions...

### ISSUE THREAD

**Issue by moar55** [ecaresoft/ecs-tests#4]
Hello there!
I am looking forward to this task, but I just have a few questions to ask...
First of all the `MTax` class implements the `Constant` class  which isn't imported anywhere, so I would like to know which Constant class it implements and if this implementation will add to the task.
Secondly, the `TaxsByListId` method is not implemented anywhere so I am just making sure I am expected to create this method, and I am not missing out on something.
Thank you :smile:

**Comment by benoror** [comment]
Don't worry about `Constant class`, nor the `TaxsByListId` method, it's not importat for the scope of the test :)
